const calendarOptions = {
	allDayDefault: null,
	allDayHtml: null,
	allDayMaintainDuration: null,
	allDaySlot: null,
	allDayText: null,
	aspectRatio: null,
	bootstrapFontAwesome: null,
	businessHours: null,
	buttonIcons: null,
	buttonText: null,
	cmdFormatter: null,
	columnHeader: null,
	columnHeaderFormat: null,
	columnHeaderHtml: null,
	columnHeaderText: null,
	contentHeight: null,
	customButtons: null,
	dateAlignment: null,
	dateIncrement: null,
	dayCount: null,
	dayPopoverFormat: null,
	defaultAllDayEventDuration: null,
	defaultDate: null,
	defaultRangeSeparator: null,
	defaultTimedEventDuration: null,
	defaultView: null,
	dir: null,
	displayEventEnd: null,
	displayEventTime: null,
	dragRevertDuration: null,
	dragScroll: null,
	dropAccept: null,
	droppable: null,
	duration: null,
	editable: null,
	endParam: null,
	eventAllow: null,
	eventBackgroundColor: null,
	eventBorderColor: null,
	eventClassName: null,
	eventClassNames: null,
	eventColor: null,
	eventConstraint: null,
	eventDataTransform: null,
	eventDragMinDistance: null,
	eventDurationEditable: null,
	eventLimit: null,
	eventLimitClick: null,
	eventLimitText: null,
	eventLongPressDelay: null,
	eventOrder: null,
	eventOverlap: null,
	eventResizableFromStart: null,
	events: null,
	eventSourceFailure: null,
	eventSources: null,
	eventSourceSuccess: null,
	eventStartEditable: null,
	eventTextColor: null,
	eventTimeFormat: null,
	firstDay: null,
	fixedWeekCount: null,
	footer: null,
	forceEventDuration: null,
	handleWindowResize: null,
	header: null,
	height: null,
	hiddenDays: null,
	lazyFetching: null,
	listDayAltFormat: null,
	listDayFormat: null,
	locale: null,
	locales: null,
	longPressDelay: null,
	maxTime: null,
	minTime: null,
	navLinkDayClick: null,
	navLinks: null,
	navLinkWeekClick: null,
	nextDayThreshold: null,
	noEventsMessage: null,
	now: null,
	nowIndicator: null,
	plugins: null,
	progressiveEventRendering: null,
	rerenderDelay: null,
	schedulerLicenseKey: null,
	scrollTime: null,
	selectable: null,
	selectAllow: null,
	selectConstraint: null,
	selectLongPressDelay: null,
	selectMinDistance: null,
	selectMirror: null,
	selectOverlap: null,
	showNonCurrentDates: null,
	slotDuration: null,
	slotEventOverlap: null,
	slotLabelFormat: null,
	slotLabelInterval: null,
	snapDuration: null,
	startParam: null,
	themeSystem: null,
	timeGridEventMinHeight: null,
	timeZone: null,
	timeZoneParam: null,
	titleFormat: null,
	titleRangeSeparator: null,
	unselectAuto: null,
	unselectCancel: null,
	validRange: null,
	views: null,
	visibleRange: null,
	weekends: null,
	weekLabel: null,
	weekNumberCalculation: null,
	weekNumbers: null,
	weekNumbersWithinDays: null,
	windowResizeDelay: null,
};

const calendarOptionsArray = Object.keys(calendarOptions);

export function getCalendarProps(props) {
	const calendarProps = {};

	for (const key of Object.keys(props)) {
		if (calendarOptionsArray.includes(key)) {
			calendarProps[key] = props[key];
		}
	}

	return calendarProps;
}
